import type { Trade } from "@/shared/types/trade";

function id(n: number): string {
  return `seed-${String(n).padStart(3, "0")}`;
}

function iso(y: number, m: number, d: number): string {
  return new Date(y, m - 1, d).toISOString();
}

const now = new Date().toISOString();

export const SEED_TRADES: Trade[] = [
  // --- Long / Closed / Win ---
  {
    id: id(1),
    ticker: "AAPL",
    direction: "long",
    status: "closed",
    entryPrice: 172.5,
    exitPrice: 189.2,
    quantity: 50,
    entryDate: iso(2024, 9, 5),
    exitDate: iso(2024, 9, 20),
    pnl: 835,
    pnlPercent: 9.68,
    tags: ["breakout", "earnings"],
    reasoning: "실적 발표 전 기술적 지지선 확인 후 진입. 거래량 증가 확인.",
    reflection:
      "실적 서프라이즈로 목표가 초과 달성. 분할 매도했으면 더 좋았을 것.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: id(2),
    ticker: "NVDA",
    direction: "long",
    status: "closed",
    entryPrice: 450.0,
    exitPrice: 520.8,
    quantity: 20,
    entryDate: iso(2024, 10, 2),
    exitDate: iso(2024, 10, 18),
    pnl: 1416,
    pnlPercent: 15.73,
    tags: ["momentum", "AI"],
    reasoning: "AI 반도체 수요 증가 사이클. 20일선 반등 확인 후 진입.",
    reflection: "강한 추세였으나 너무 일찍 청산. 트레일링 스탑을 활용할 것.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: id(3),
    ticker: "TSLA",
    direction: "long",
    status: "closed",
    entryPrice: 238.0,
    exitPrice: 265.5,
    quantity: 30,
    entryDate: iso(2024, 10, 10),
    exitDate: iso(2024, 11, 1),
    pnl: 825,
    pnlPercent: 11.55,
    tags: ["swing", "momentum"],
    reasoning: "전기차 인도량 발표 호조 + 차트 삼각수렴 상향 돌파.",
    reflection:
      "변동성이 커서 중간에 흔들렸으나 계획대로 홀드. 멘탈 관리 중요.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: id(4),
    ticker: "GOOGL",
    direction: "long",
    status: "closed",
    entryPrice: 138.5,
    exitPrice: 152.3,
    quantity: 60,
    entryDate: iso(2024, 11, 5),
    exitDate: iso(2024, 11, 22),
    pnl: 828,
    pnlPercent: 9.96,
    tags: ["breakout"],
    reasoning: "클라우드 성장률 가속 뉴스 + 52주 신고가 돌파 시도.",
    reflection: "신고가 돌파 매매는 성공률이 높다. 리스크 대비 리워드 좋았음.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: id(5),
    ticker: "MSFT",
    direction: "long",
    status: "closed",
    entryPrice: 375.0,
    exitPrice: 410.2,
    quantity: 15,
    entryDate: iso(2024, 11, 12),
    exitDate: iso(2024, 12, 5),
    pnl: 528,
    pnlPercent: 9.39,
    tags: ["swing", "AI"],
    reasoning: "Copilot 매출 성장 기대감. 장기 상승 채널 하단 지지 확인.",
    reflection: "안정적인 우량주 스윙. 포지션 사이즈를 더 키워도 됐을 것.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: id(6),
    ticker: "AMZN",
    direction: "long",
    status: "closed",
    entryPrice: 178.0,
    exitPrice: 195.5,
    quantity: 40,
    entryDate: iso(2024, 12, 3),
    exitDate: iso(2024, 12, 20),
    pnl: 700,
    pnlPercent: 9.83,
    tags: ["earnings", "breakout"],
    reasoning: "AWS 성장 재가속 + 연말 쇼핑 시즌 기대감으로 진입.",
    reflection: "예상대로 움직임. 진입 타이밍이 정확했다.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: id(7),
    ticker: "META",
    direction: "long",
    status: "closed",
    entryPrice: 510.0,
    exitPrice: 560.8,
    quantity: 10,
    entryDate: iso(2025, 1, 8),
    exitDate: iso(2025, 1, 24),
    pnl: 508,
    pnlPercent: 9.96,
    tags: ["momentum"],
    reasoning: "광고 매출 호조 전망 + Reels 수익화 가속 기대.",
    reflection: "수익 실현 시점이 적절했음. 다만, 이후 추가 상승분을 놓침.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: id(8),
    ticker: "AAPL",
    direction: "long",
    status: "closed",
    entryPrice: 185.0,
    exitPrice: 178.5,
    quantity: 40,
    entryDate: iso(2025, 1, 15),
    exitDate: iso(2025, 1, 28),
    pnl: -260,
    pnlPercent: -3.51,
    tags: ["swing"],
    reasoning: "아이폰 판매 호조 예상으로 진입했으나, 중국 매출 우려 부각.",
    reflection: "매크로 리스크를 과소평가. 손절 라인을 지켰으나 아쉬운 매매.",
    createdAt: now,
    updatedAt: now,
  },
  // --- Short / Closed / Win ---
  {
    id: id(9),
    ticker: "RIVN",
    direction: "short",
    status: "closed",
    entryPrice: 18.5,
    exitPrice: 14.2,
    quantity: 200,
    entryDate: iso(2024, 10, 15),
    exitDate: iso(2024, 11, 5),
    pnl: 860,
    pnlPercent: 23.24,
    tags: ["breakdown"],
    reasoning: "생산 목표 하향 + 현금 소진 우려. 지지선 이탈 확인 후 숏.",
    reflection: "숏 포지션에서 큰 수익. 리스크 관리가 잘 된 매매였음.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: id(10),
    ticker: "SNAP",
    direction: "short",
    status: "closed",
    entryPrice: 12.8,
    exitPrice: 9.5,
    quantity: 300,
    entryDate: iso(2024, 11, 20),
    exitDate: iso(2024, 12, 10),
    pnl: 990,
    pnlPercent: 25.78,
    tags: ["earnings", "breakdown"],
    reasoning: "광고 매출 둔화 + 사용자 성장 정체. 실적 미스 예상.",
    reflection: "정확한 분석이었음. 숏 커버 시점도 적절했다.",
    createdAt: now,
    updatedAt: now,
  },
  // --- Short / Closed / Loss ---
  {
    id: id(11),
    ticker: "GME",
    direction: "short",
    status: "closed",
    entryPrice: 22.0,
    exitPrice: 28.5,
    quantity: 100,
    entryDate: iso(2024, 12, 5),
    exitDate: iso(2024, 12, 12),
    pnl: -650,
    pnlPercent: -29.55,
    tags: ["squeeze"],
    reasoning: "펀더멘탈 대비 고평가 판단으로 숏 진입.",
    reflection: "밈 주식 숏은 위험. 소셜 미디어 센티먼트를 과소평가.",
    createdAt: now,
    updatedAt: now,
  },
  // --- Long / Closed / Loss ---
  {
    id: id(12),
    ticker: "INTC",
    direction: "long",
    status: "closed",
    entryPrice: 38.5,
    exitPrice: 33.2,
    quantity: 80,
    entryDate: iso(2025, 1, 3),
    exitDate: iso(2025, 1, 17),
    pnl: -424,
    pnlPercent: -13.77,
    tags: ["value"],
    reasoning: "파운드리 사업 턴어라운드 기대감으로 진입.",
    reflection: "턴어라운드 매매는 시간이 오래 걸림. 인내심 부족으로 손실.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: id(13),
    ticker: "BA",
    direction: "long",
    status: "closed",
    entryPrice: 205.0,
    exitPrice: 192.0,
    quantity: 25,
    entryDate: iso(2024, 12, 18),
    exitDate: iso(2025, 1, 8),
    pnl: -325,
    pnlPercent: -6.34,
    tags: ["value", "swing"],
    reasoning: "항공 수요 회복 기대 + 저점 매수 시도.",
    reflection: "품질 이슈 뉴스로 급락. 이벤트 리스크 관리 필요.",
    createdAt: now,
    updatedAt: now,
  },
  // --- Open positions ---
  {
    id: id(14),
    ticker: "NVDA",
    direction: "long",
    status: "open",
    entryPrice: 480.0,
    quantity: 15,
    entryDate: iso(2025, 1, 27),
    tags: ["momentum", "AI"],
    reasoning:
      "차세대 GPU 출시 앞두고 사전 포지셔닝. 기술적 조정 후 반등 구간.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: id(15),
    ticker: "TSLA",
    direction: "short",
    status: "open",
    entryPrice: 275.0,
    quantity: 20,
    entryDate: iso(2025, 1, 30),
    tags: ["swing"],
    reasoning: "단기 과매수 구간. RSI 80 이상에서 숏 진입. 목표가 250.",
    createdAt: now,
    updatedAt: now,
  },
];
